// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THEONEEAD.Infrastructure.Persistence.Seminario;

#nullable disable

namespace THEONEEAD.Infrastructure.Migrations
{
    [DbContext(typeof(SeminarioDbContext))]
    partial class SeminarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("THEONEEAD.Domain.Entities.Conteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConteudoTexto")
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<Guid>("DisciplinaEADId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("DuracaoSegundos")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UrlSlides")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("UrlVideo")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaEADId", "Ordem");

                    b.ToTable("Conteudo", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.CursoEAD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("CursoLegadoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Sequencial")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CursoLegadoId")
                        .IsUnique();

                    b.ToTable("CursoEAD", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.Dependencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DestinoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrigemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrigemId", "DestinoId", "Tipo")
                        .IsUnique();

                    b.ToTable("Dependencia", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.DisciplinaEAD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CursoEADId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoEADId", "Ordem");

                    b.ToTable("DisciplinaEAD", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("login");

                    b.Property<byte>("Perfil")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("perfil");

                    b.Property<string>("PrimeiroAcesso")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("primeiro_acesso");

                    b.Property<string>("RecuperaSenha")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("recupera_senha");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("senha");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuarios_ead", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Infrastructure.Persistence.Seminario.Entities.AlunoCurso", b =>
                {
                    b.Property<long>("AlunoId")
                        .HasColumnType("bigint");

                    b.Property<long>("CursoId")
                        .HasColumnType("bigint");

                    b.HasKey("AlunoId", "CursoId");

                    b.ToTable("legado_aluno_curso", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Infrastructure.Persistence.Seminario.Entities.Estudante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("estudantes", (string)null);
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.Conteudo", b =>
                {
                    b.HasOne("THEONEEAD.Domain.Entities.DisciplinaEAD", "Disciplina")
                        .WithMany("Conteudos")
                        .HasForeignKey("DisciplinaEADId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.DisciplinaEAD", b =>
                {
                    b.HasOne("THEONEEAD.Domain.Entities.CursoEAD", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoEADId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.CursoEAD", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("THEONEEAD.Domain.Entities.DisciplinaEAD", b =>
                {
                    b.Navigation("Conteudos");
                });
#pragma warning restore 612, 618
        }
    }
}
